FROM python:3.11

WORKDIR /app

# Install dependencies
COPY backend/requirements.txt .
RUN pip install -r requirements.txt

# Copy all app files
COPY . .

# Expose port used by Flask
EXPOSE 8000

# Run Flask app directly
CMD ["python", "backend/main.py"]